name: Go CI + Multi-Arch Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      # 3. 安装依赖
      - name: Install dependencies
        run: go mod tidy

      # 4. 运行测试
      - name: Run tests
        run: go test ./... -v

      # 5. 构建二进制（确保能编译通过） 
      - name: Build binary
        run: go build -o go-ci-demo .

      # 6. 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. 设置 buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 生成镜像版本号
      - name: Generate version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "检测到 Git Tag: $VERSION"
          elif [[ -n "${GITHUB_SHA}" ]]; then
            VERSION=$(echo "${GITHUB_SHA}" | cut -c1-7)
            echo "使用 Commit SHA: $VERSION"
          else
            VERSION=$(date +'%Y%m%d%H%M%S')
            echo "使用 时间戳: $VERSION"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 构建并推送镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/go-ci-demo:latest
            ${{ secrets.DOCKER_USERNAME }}/go-ci-demo:${{ env.VERSION }}